version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels: ["dependencies"]
    commit-message:
      prefix: "deps"  
      include: "scope"
    groups:
      androidX:
        patterns:
          - "androidx.*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
      firebase:
        patterns:
          - "com.google.firebase*"
      mlkit:
        patterns:
          - "com.google.mlkit*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["ci", "dependencies"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
